-- MySQL Script generated by MySQL Workbench
-- Mon Jun 29 15:40:52 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema blog-loovies
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema blog-loovies
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blog-loovies` DEFAULT CHARACTER SET utf8 ;
USE `blog-loovies` ;

-- -----------------------------------------------------
-- Table `blog-loovies`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog-loovies`.`User` ;

CREATE TABLE IF NOT EXISTS `blog-loovies`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(125) NULL,
  `password` VARCHAR(45) NULL,
  `role` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `surname` VARCHAR(45) NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog-loovies`.`Post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog-loovies`.`Post` ;

CREATE TABLE IF NOT EXISTS `blog-loovies`.`Post` (
  `idPost` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NULL,
  `titre` VARCHAR(125) NULL,
  `text` LONGTEXT NULL,
  `img` VARCHAR(45) NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idPost`, `User_idUser`),
  UNIQUE INDEX `idPost_UNIQUE` (`idPost` ASC) VISIBLE,
  INDEX `fk_Post_User_idx` (`User_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_Post_User`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `blog-loovies`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog-loovies`.`Faq`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog-loovies`.`Faq` ;

CREATE TABLE IF NOT EXISTS `blog-loovies`.`Faq` (
  `idFaq` INT NOT NULL AUTO_INCREMENT,
  `questions` LONGTEXT NULL,
  `answer` LONGTEXT NULL,
  PRIMARY KEY (`idFaq`),
  UNIQUE INDEX `idFaq_UNIQUE` (`idFaq` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog-loovies`.`Newsletter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog-loovies`.`Newsletter` ;

CREATE TABLE IF NOT EXISTS `blog-loovies`.`Newsletter` (
  `idNewsletter` INT NOT NULL AUTO_INCREMENT,
  `mail` VARCHAR(45) NULL,
  PRIMARY KEY (`idNewsletter`),
  UNIQUE INDEX `idNewsletter_UNIQUE` (`idNewsletter` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog-loovies`.`Contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog-loovies`.`Contact` ;

CREATE TABLE IF NOT EXISTS `blog-loovies`.`Contact` (
  `idContact` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `surname` VARCHAR(45) NULL,
  `mail` VARCHAR(45) NULL,
  `message` LONGTEXT NULL,
  PRIMARY KEY (`idContact`),
  UNIQUE INDEX `idContact_UNIQUE` (`idContact` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog-loovies`.`customize`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog-loovies`.`customize` ;

CREATE TABLE IF NOT EXISTS `blog-loovies`.`customize` (
  `idcustomize` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL,
  `title` VARCHAR(45) NULL,
  `link` VARCHAR(45) NULL,
  `copyright` VARCHAR(45) NULL,
  PRIMARY KEY (`idcustomize`),
  UNIQUE INDEX `idcustomize_UNIQUE` (`idcustomize` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog-loovies`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog-loovies`.`category` ;

CREATE TABLE IF NOT EXISTS `blog-loovies`.`category` (
  `idcategory` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idcategory`),
  UNIQUE INDEX `idcategory_UNIQUE` (`idcategory` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog-loovies`.`media`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog-loovies`.`media` ;

CREATE TABLE IF NOT EXISTS `blog-loovies`.`media` (
  `idmedia` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `format` VARCHAR(45) NULL,
  `date_add` DATETIME NULL,
  `date_updated` DATETIME NULL,
  `active` TINYINT(1) NULL,
  `Post_idPost` INT NOT NULL,
  `customize_idcustomize` INT NOT NULL,
  PRIMARY KEY (`idmedia`, `Post_idPost`, `customize_idcustomize`),
  UNIQUE INDEX `idimage_UNIQUE` (`idmedia` ASC) VISIBLE,
  INDEX `fk_media_Post1_idx` (`Post_idPost` ASC) VISIBLE,
  INDEX `fk_media_customize1_idx` (`customize_idcustomize` ASC) VISIBLE,
  CONSTRAINT `fk_media_Post1`
    FOREIGN KEY (`Post_idPost`)
    REFERENCES `blog-loovies`.`Post` (`idPost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_media_customize1`
    FOREIGN KEY (`customize_idcustomize`)
    REFERENCES `blog-loovies`.`customize` (`idcustomize`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog-loovies`.`category_has_Post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog-loovies`.`category_has_Post` ;

CREATE TABLE IF NOT EXISTS `blog-loovies`.`category_has_Post` (
  `category_idcategory` INT NOT NULL,
  `Post_idPost` INT NOT NULL,
  `Post_User_idUser` INT NOT NULL,
  PRIMARY KEY (`category_idcategory`, `Post_idPost`, `Post_User_idUser`),
  INDEX `fk_category_has_Post_Post1_idx` (`Post_idPost` ASC, `Post_User_idUser` ASC) VISIBLE,
  INDEX `fk_category_has_Post_category1_idx` (`category_idcategory` ASC) VISIBLE,
  CONSTRAINT `fk_category_has_Post_category1`
    FOREIGN KEY (`category_idcategory`)
    REFERENCES `blog-loovies`.`category` (`idcategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_category_has_Post_Post1`
    FOREIGN KEY (`Post_idPost` , `Post_User_idUser`)
    REFERENCES `blog-loovies`.`Post` (`idPost` , `User_idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
